export const products = [
  {
    id: "1",
    title: "Apple iMac",
    description: "Apple iMac 21.5 Desktop i5-4570R 2.7GHz",
    price: "80,000",
    image: "/Images/product1.jpg",
  },
  {
    id: "2",
    title: "Special Gifts",
    description: "Buyist Message Pills Gift Set",
    price: "4000",
    image: "/Images/product2.jpg",
  },
  {
    id: "3",
    title: "Milton Flask",
    description: "MILTON Flip Lid 1000 ml Flask",
    price: "80,000",
    image: "/Images/product3.jpg",
  },
  {
    id: "4",
    title: "Teddy bear",
    description: "Cute Teddy Bear - 30 cm  (Pink)",
    price: "600",
    image: "/Images/product4.jpg",
  },
  {
    id: "5",
    title: "Clock",
    description: "Kadio Analog 20 cm X 20 cm Clock",
    price: "399",
    image: "/Images/product5.jpg",
  },
  {
    id: "6",
    title: "Dell Laptop",
    description: "DELL Inspiron Athlon Dual Core 3050U",
    price: "80,000",
    image: "/Images/product6.jpg",
  },
  {
    id: "7",
    title: "Red wine",
    description: "Toselli Non Alcoholic Red Wine, 750ml",
    price: "80,000",
    image: "/Images/product7.jpg",
  },
  {
    id: "8",
    title: "Coolers",
    description: "Spectacle Frames for Men Women",
    price: "900",
    image: "/Images/product8.jpg",
  },
  {
    id: "9",
    title: "Samsung SSD",
    description: "Samsung 980 500GB Up to 3,500 MB/s ",
    price: "5,999",
    image: "/Images/product9.jpg",
  },
  {
    id: "10",
    title: "Samsung Galaxy",
    description: "Samsung Galaxy Note 8 (Maple Gold/6GB)",
    price: "32,000",
    image: "/Images/product10.jpg",
  },
  {
    id: "11",
    title: "iphone X",
    description: "Apple iPhone X 64GB",
    price: "80,000",
    image: "/Images/product11.jpg",
  },
];
